import Header from "../../Header";

const Valguero = () => {
    return  (    <div> <Header/> <div className="valgueroDinos">

    <a href="/maps/valguero/anglerfish">Aberrant Anglerfish</a>
    <a href="/maps/valguero/araneo">Aberrant Araneo</a>
    <a href="/maps/valguero/baryonyx">Aberrant Baryonyx</a>
    <a href="/maps/valguero/beelzebufo">Aberrant Beelzebufo</a>
    <a href="/maps/valguero/carbonemys">Aberrant Carbonemys</a>
    <a href="/maps/valguero/dimetrodon">Aberrant Dimetrodon</a>
    <a href="/maps/valguero/dimorphodon">Aberrant Dimorphodon</a>
    <a href="/maps/valguero/diplocaulus">Aberrant Diplocaulus</a>
    <a href="/maps/valguero/diplodocus">Aberrant Diplodocus</a>
    <a href="/maps/valguero/direbear">Aberrant Dire Bear</a>
    <a href="/maps/valguero/dodo">Aberrant Dodo</a>
    <a href="/maps/valguero/doedicurus">Aberrant Doedicurus</a>
    <a href="/maps/valguero/electrophorus">Aberrant Electrophorus</a>
    <a href="/maps/valguero/equus">Aberrant Equus</a>
    <a href="/maps/valguero/iguanodon">Aberrant Iguanodon</a>
    <a href="/maps/valguero/lystrosaurus">Aberrant Lystrosaurus</a>
    <a href="/maps/valguero/moschops">Aberrant Moschops</a>
    <a href="/maps/valguero/ovis">Aberrant Ovis</a>
    <a href="/maps/valguero/paraceratherium">Aberrant Paraceratherium</a>
    <a href="/maps/valguero/parasaur">Aberrant Parasaur</a>
    <a href="/maps/valguero/pulmonoscorpius">Aberrant Pulmonoscorpius</a>
    <a href="/maps/valguero/raptor">Aberrant raptor</a>
    <a href="/maps/valguero/sarcosuchus">Aberrant Sarco</a>
    <a href="/maps/valguero/spinosaurus">Aberrant Spino</a>
    <a href="/maps/valguero/stegosaurus">Aberrant Stego</a>
    <a href="/maps/valguero/triceratops">Aberrant Triceratops</a>
    <a href="/maps/valguero/achatina">Achatina</a>
    <a href="/maps/valguero/allosaurus">Allosaurus</a>
    <a href="/maps/valguero/anglerfish">Anglerfish</a>
    <a href="/maps/valguero/ankylosaurus">Ankylosaurus</a>
    <a href="/maps/valguero/araneo">Araneo</a>
    <a href="/maps/valguero/archaeopteryx">Archaeopteryx</a>
    <a href="/maps/valguero/argentavis">Argentavis</a>
    <a href="/maps/valguero/arthropluera">Arthropluera</a>
    <a href="/maps/valguero/baryonyx">Baryonyx</a>
    <a href="/maps/valguero/basilosaurus">Basilosaurus</a>
    <a href="/maps/valguero/beelzebufo">Beelzebufo</a>
    <a href="/maps/valguero/brontosaurus">Brontosaurus</a>
    <a href="/maps/valguero/bulbdog">Bulbdog</a>
    <a href="/maps/valguero/carbonemys">Carbonemys</a>
    <a href="/maps/valguero/carnotaurus">Carnotaurus</a>
    <a href="/maps/valguero/castoroides">Castoroides</a>
    <a href="/maps/valguero/chalicotherium">Chalicotherium</a>
    <a href="/maps/valguero/compy">Compy</a>
    <a href="/maps/valguero/daeodon">Daeodon</a>
    <a href="/maps/valguero/deinonychus">Deinonychus</a>
    <a href="/maps/valguero/dilophosaur">Dilophosaur</a>
    <a href="/maps/valguero/dimetrodon">Dimetrodon</a>
    <a href="/maps/valguero/dimorphodon">Dimorphodon</a>
    <a href="/maps/valguero/diplocaulus">Diplocaulus</a>
    <a href="/maps/valguero/diplodocus">Diplodocus</a>
    <a href="/maps/valguero/direbear">Dire Bear</a>
    <a href="/maps/valguero/direwolf">Direwolf</a>
    <a href="/maps/valguero/dodo">Dodo</a>
    <a href="/maps/valguero/doedicurus">Doedicurus</a>
    <a href="/maps/valguero/dunkleosteus">Dunkleosteus</a>
    <a href="/maps/valguero/electrophorus">Electrophorus</a>
    <a href="/maps/valguero/equus">Equus</a>
    <a href="/maps/valguero/featherlight">Featherlight</a>
    <a href="/maps/valguero/gallimimus">Gallimimus</a>
    <a href="/maps/valguero/giganotosaurus">Giganotosaurus</a>
    <a href="/maps/valguero/gigantopithecus">Gigantopithecus</a>
    <a href="/maps/valguero/glowtail">Glowtail</a>
    <a href="/maps/valguero/hesperonis">Hesperonis</a>
    <a href="/maps/valguero/hyaenodon">Hyaenodon</a>
    <a href="./maps/valguero/wyvern">Wyvern</a>
    <a href="/maps/valguero/ichthyornis">Ichthyornis</a>
    <a href="/maps/valguero/ichthyosaurus">Ichthyosaurus</a>
    <a href="/maps/valguero/iguanodon">Iguanodon</a>
    <a href="/maps/valguero/jerboa">Jerboa</a>
    <a href="/maps/valguero/kairuku">Kairuku</a>
    <a href="/maps/valguero/kaprosuchus">Kaprosuchus</a>
    <a href="/maps/valguero/kentrosaurus">Kentrosaurus</a>
    <a href="/maps/valguero/lymantria">Lymantria</a>
    <a href="/maps/valguero/lystrosaurus">Lystrosaurus</a>
    <a href="/maps/valguero/mammoth">Mammoth</a>
    <a href="/maps/valguero/manta">Manta</a>
    <a href="/maps/valguero/mantis">Mantis</a>
    <a href="/maps/valguero/megaloceros">Megaloceros</a>
    <a href="/maps/valguero/megalodon">Megalodon</a>
    <a href="/maps/valguero/megatherium">Megatherium</a>
    <a href="/maps/valguero/mesopithecus">Mesopithecus</a>
    <a href="/maps/valguero/microraptor">Microraptor</a>
    <a href="/maps/valguero/mosasaurus">Mosasaurus</a>
    <a href="/maps/valguero/moschops">Moschops</a>
    <a href="/maps/valguero/onyc">Onyc</a>
    <a href="/maps/valguero/otter">Otter</a>
    <a href="/maps/valguero/oviraptor">Oviraptor</a>
    <a href="/maps/valguero/ovis">Ovis</a>
    <a href="/maps/valguero/pachy">Pachy</a>
    <a href="/maps/valguero/pachyrhinosaurus">Pachyrhinosaurus</a>
    <a href="/maps/valguero/paraceratherium">Paraceratherium</a>
    <a href="/maps/valguero/parasaur">Parasaur</a>
    <a href="/maps/valguero/pegomastax">Pegomastax</a>
    <a href="/maps/valguero/pelagornis">Pelagornis</a>
    <a href="/maps/valguero/phiomia">Phiomia</a>
    <a href="/maps/valguero/plesiosaur">Plesiosaur</a>
    <a href="/maps/valguero/procoptodon">Procoptodon</a>
    <a href="/maps/valguero/pteranodon">Pteranodon</a>
    <a href="/maps/valguero/pulmonoscorpius">Pulmonoscorpius</a>
    <a href="/maps/valguero/purlovia">Purlovia</a>
    <a href="/maps/valguero/quetzalcoatlus">Quetzal</a>
    <a href="/maps/valguero/raptor">Raptor</a>
    <a href="/maps/valguero/ravager">Ravager</a>
    <a href="/maps/valguero/rex">Rex</a>
    <a href="/maps/valguero/rollrat">Roll Rat</a>
    <a href="/maps/valguero/sabertooth">Sabertooth</a>
    <a href="/maps/valguero/sarcosuchus">Sarco</a>
    <a href="/maps/valguero/spinosaurus">Spino</a>
    <a href="/maps/valguero/stegosaurus">Stego</a>
    <a href="/maps/valguero/tapejara">Tapejara</a>
    <a href="/maps/valguero/terrorbird">Terror Bird</a>
    <a href="/maps/valguero/therizinosaur">Therizinosaur</a>
    <a href="/maps/valguero/thylacoleo">Thylacoleo</a>
    <a href="/maps/valguero/triceratops">Triceratops</a>
    <a href="/maps/valguero/troodon">Troodon</a>
    <a href="/maps/valguero/tusoteuthis">Tusoteuthis</a>
    <a href="/maps/valguero/equus">Unicorn</a>
    <a href="/maps/valguero/woollyrhino">Woolly Rhino</a>
    <a href="/maps/valguero/yutyrannus">Yutyrannus</a>
</div>
</div>
)
}

export default Valguero;